backend/controllers/PaymentController.php
<?php

namespace backend\controllers;

use Yii;
use app\models\Pages;
use app\models\PaymentsList;
use app\models\PaymentsCountry;
use yii\data\ActiveDataProvider;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * Payment controller
 */
class PaymentController extends Controller
{

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => PaymentsList::find(),
            'sort'=> ['defaultOrder' => ['payment_id' => SORT_ASC]]
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate()
    {
       $model = new PaymentsList();
       $countries = new PaymentsCountry();

       if ($model->load(Yii::$app->request->post()) && $model->save()) {
          if (Yii::$app->request->post('PaymentsCountry')) {
            foreach (Yii::$app->request->post('PaymentsCountry')['country_id'] as $country_id) {
              $pc = new PaymentsCountry();
              $pc->payment_id = $model->payment_id;
              $pc->country_id = $country_id;
              $pc->save();
            }
          }
          return $this->redirect(['index']);
       } else {
           return $this->render('create', [
              'model' => $model,
              'countries' => $countries
           ]);
       }
    }

    public function actionUpdate($id)
    {
       $model = $this->findModel($id);
       $countries = PaymentsCountry::find()->where(['payment_id' => $id])->asArray()->all();
       $tmp = [];
       foreach ($countries as $data) {
         $tmp[] = $data['country_id'];
       }
       $countries = $tmp;
       //var_dump($countries);return;
       if ($model->load(Yii::$app->request->post()) && $model->save()) {
          PaymentsCountry::deleteAll('payment_id = :payment_id', ['payment_id' => $id]);
          if (Yii::$app->request->post('PaymentsCountry')) {
            foreach (Yii::$app->request->post('PaymentsCountry')['country_id'] as $country_id) {
              $pc = new PaymentsCountry();
              $pc->payment_id = $model->payment_id;
              $pc->country_id = $country_id;
              $pc->save();
            }
          }
          return $this->redirect(['index']);
       } else {
           return $this->render('update', [
              'model' => $model,
              'countries' => $countries
           ]);
       }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = PaymentsList::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/PaymentController.php
<?php

namespace frontend\controllers;


use Yii;
use common\models\User;
use frontend\models\Advertiser;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use frontend\actions\AdvertiserEventFeedAction;
use frontend\actions\BookAction;
use common\models\Refund;
use common\helpers\Payment;
use common\helpers\Toolbox;


class PaymentController extends Controller
{

    public $layout = 'nonadvertiser';



    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
//						'actions' => ['skrill', 'skrill-redirect'],
                        'actions' => ['index', 'refund'],
                        'roles' => ['@'],
                    ],
                /*
                  [
                  'allow'	 => true,
                  'actions' => ['manage'],
                  'roles'	 => ['Advertiser'],
                  ],
                 * 
                 */
                ],
            ],
        ];
    }


    public function actions()
    {
        return [
            'refund' => \frontend\actions\CreateRefundAction::className(),
        ];
    }


    public function actionIndex($amount = 100.00)
    {
        $errors = false;

        if (!Toolbox::currentUser()) {
            throw new \yii\web\HttpException(403, 'Access Denied.');
        }

        if (Yii::$app->request->isPost) {

            if (empty($_POST['stripeToken']) || empty($_POST['amount'])) {
                throw new \yii\web\HttpException(400, 'Bad Request.');
            }

            $token = $_POST['stripeToken'];
            $amount = $_POST['amount'];
            try {
                if (!Toolbox::currentUser()->stripe_id) {
                    $customer = Yii::$app->stripe->createCustomer(Toolbox::currentUser()->email, $token);
                    Toolbox::currentUser()->stripe_id = $customer->id;
                    Toolbox::currentUser()->save(false, ['stripe_id']);
                } else {
                    $customer = Yii::$app->stripe->retrieveCustomer(Toolbox::currentUser()->stripe_id);
                    $customer->source = $token;
                    $customer->save();
                }

                $charge = Yii::$app->stripe->createCharge($customer->id, round($amount*100), 'usd', null, [
                    'description' => Payment::REASON_REFILL,
                ]);
            } catch (\Exception $ex) {
                Yii::$app->session->setFlash('error', $ex->getMessage());
                $this->refresh();
                Yii::$app->end();
            }

            $t = Payment::createRefillTransaction($amount, Toolbox::currentUser(), $charge->id, \common\models\Transaction::GATEWAY_STRIPE, true);
            $t->commit();
            Yii::$app->session->setFlash('success', Yii::t('booking', 'Payment {sum} successfully done. Your funds refilled.', ['sum' => Toolbox::formatMoney($amount)]));
            $this->refresh();
            Yii::$app->end();

            //Array ( [_csrf] => SWtlZzFlRG8aAFMpQjcRVnAuLlAAAwYMexMuPlojKl4zNB9fRFFxHg== [amount] => 100 [stripeToken] => src_18tQOeBHaS5ztdCHdXLq0F0k )
        }

        $refund = new Refund();
        $refund->user_id = Toolbox::currentUser()->id;
        $refund->user_email = Toolbox::currentUser()->email;
        $params = ['amount' => $amount, 'errors' => $errors, 'refund' => $refund];
        return $this->render('index', $params);
    }

    /*
      public function actionIndex($amount = 100.00)
      {
      $errors = false;
      if (Yii::$app->request->isPost) {
      if (empty($_POST['amount']) || empty($_POST['payment_method_nonce'])) {
      throw new \yii\web\BadRequestHttpException();
      }

      $amount = $_POST['amount'];
      $btt = Yii::$app->braintree->doTransactionSale(floatval($_POST['amount']), $_POST['payment_method_nonce']);

      if (!$btt) {
      $errors = Yii::$app->braintree->errors;
      } elseif (Yii::$app->braintree->isStatusValid($btt->status)) {
      $t = Payment::createRefillTransaction($amount, Toolbox::currentNonAdvertiser(), $btt->id, 'Braintree', true);
      $t->commit();
      Yii::$app->session->setFlash('success', Yii::t('booking', 'Payment {sum} successfully done.', ['sum' => Toolbox::formatMoney($amount)]));
      $this->refresh();
      Yii::$app->end();
      } else {
      //TODO: fail on braintree side
      }
      }
      $refund = new Refund();
      $refund->user_id = Toolbox::currentUser()->id;
      $refund->user_email = Toolbox::currentUser()->email;
      $params = ['amount' => $amount,'errors' => $errors, 'refund' => $refund];
      return $this->render('index', $params);
      }
     * 
     */

    /*
      public function actionSkrill($amount = null)
      {
      $params = [];
      $params['model'] = $model = Yii::$app->skrill->createForm(['amount' => $amount ? $amount : 100]);
      $model->validate();

      return $this->render('skrill', $params);
      }


      public function actionSkrillRedirect()
      {
      if (Yii::$app->request->isPost) {
      Yii::$app->skrill->getSessionId($_POST);
      }
      }
     * 
     */




    /*
      public function beforeAction($action)
      {
      if ($action->id === 'index') {
      //$this->enableCsrfValidation = false;
      }

      return parent::beforeAction($action);
      }
     * 
     */

}

frontend/views/payment/_refund_form.php
<?php

/**
 * @var $form \yii\widgets\ActiveForm
 */
use yii\helpers\Html;


$form = \yii\widgets\ActiveForm::begin([
    'id' => 'login-form',
    'action' => \yii\helpers\Url::to(['payment/refund']),
    'options' => ['class' => 'form-horizontal'],
    'enableAjaxValidation' => true,
]);
?>

<?= $form->field($model, 'amount')->textInput(['type' => 'number']); ?>
<?= $form->field($model, 'description')->textarea(); ?>
<?= Html::submitButton('Create Refund Request', ['class' => 'btn btn-green']); ?>

<?php \yii\widgets\ActiveForm::end(); ?>

frontend/views/payment/braintree.php
Braintree

frontend/views/payment/index.php
<?php

use Yii;
use yii\helpers\Url;
use common\helpers\Toolbox;
use frontend\widgets\NonAdvInfo;
use frontend\widgets\AdvInfo;
use yii\widgets\ActiveForm;
use common\helpers\Payment;


//Yii::$app->braintree->jsRegister($this);
//Yii::$app->braintree->jsInitForm($this, 'payment-form');
common\assets\ProjectAsset::register($this);
?>

<div class="user-col">
    <?php if (Toolbox::currentNonAdvertiser()) : ?>
        <?=
        NonAdvInfo::widget([
            'user' => Toolbox::currentNonAdvertiser(),
            'payments' => []
        ]);
        ?>
    <?php elseif (Toolbox::currentAdvertiser()) : ?>
        <?php
        echo AdvInfo::widget([
            'id' => Toolbox::currentUser()->id,
            'advertiser' => Toolbox::currentAdvertiser()
        ]);
        ?>
    <?php endif; ?>
</div>
<div class="booking-col">
    <?php if (Toolbox::currentNonAdvertiser()) : ?>
        <h2>Refill Balance</h2>
        <?php
        $form = ActiveForm::begin([
            'action' => Url::to(['payment/index']),
            'method' => 'POST',
            'id' => "stripe-checkout",
        ]);
        ?>
        <label for="amount">Amount</label>
        <input type="text" name="amount" value="<?= $amount; ?>" id="amount">
        <input type="hidden" value="" name="stripeToken" id="stripe-token">
        <button id='checkoutButton'>Checkout</button>
        <!--
    <form action="<?= Url::to(['payment/index']); ?>" method="POST" id="stripe-checkout">
        
        <script
            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<?= Yii::$app->stripe->publicKey; ?>"
            data-amount="<?= str_replace('.', '', Toolbox::formatMoney($amount, false)); ?>"
            data-name="Xclusivo"
            data-description="<?= \common\helpers\Payment::REASON_REFILL; ?>"
            data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
            data-label="Pay with Card or Bitcoin"
            data-locale="auto"
            data-currency="usd"
            data-email="<?= Toolbox::currentNonAdvertiser()->email; ?>"
            data-bitcoin="true">
        </script>            
    </form>
        -->

        <?php ActiveForm::end(); ?>

        <script src="https://checkout.stripe.com/checkout.js"></script>

        <script>
            var handler = StripeCheckout.configure({
                key: '<?= Yii::$app->stripe->publicKey; ?>',
                locale: 'auto',
                name: 'Xclusivo',
                currency: "usd",
                bitcoin: true,
                email: '<?= Toolbox::currentNonAdvertiser()->email; ?>',
                description: '<?= \common\helpers\Payment::REASON_REFILL; ?>',
                token: function (token)
                {
                    $('#stripe-token').val(token.id);
                    $('#stripe-checkout').submit();
                }
            });

        </script>

        <?php $this->registerJs(" 
            $('#checkoutButton').on('click', function (e)
            {
                e.preventDefault();
                e.stopPropagation();

                var amount = $('input#amount').val();
                amount = amount.replace(/\$/g, '').replace(/\,/g, '')

                amount = parseFloat(amount);

                if (isNaN(amount)) {
                    project.flashMessage('".Yii::t('booking', 'Please enter a valid amount in USD (point separated number).')."', project.FM_ERROR);
                } else if (amount < ".Payment::minRefill().") {
                    project.flashMessage('".Yii::t('booking', 'Refilling amount must be at least {amount}.', ['amount' => Toolbox::formatMoney(Payment::minRefill())])."', project.FM_ERROR);
                } else {
                    amount = amount * 100; // Needs to be an integer!
                    handler.open({
                        amount: Math.round(amount)
                    })
                }
            });
            
        ", yii\web\View::POS_LOAD) ;?>
        
        <?php /*
          <form action="https://test.bitpay.com:443/checkout" method="post" >
          <input type="hidden" name="action" value="checkout" />
          <input type="hidden" name="posData" value="" />
          <input type="hidden" name="data" value="wDXnm1gtekYETA+gK5XPNXjAMhgEr3HHItQNt4riSbujEwFfVvE5qTnPLlnh8yovJdJbghWXK+w895WG1mE7vYifcwnwfI8hOLr5E5plNObaXqUa2fMn2EHVx+2fPaxfi7tpNgormhuci/NplkQzpLS1jrN3wM/6Uopxa5Wt71/53NerxtXuLvAQzyVwm6nMM0yHC8tS/dRr8AxpT14r+w==" />
          <input type="image" src="https://test.bitpay.com:443/img/button2.png" border="0" name="submit" alt="BitPay, the easy way to pay with bitcoins." >
          </form>
         * 
         */ ?>

        <?php /*
          <!--
          <form method="post" id="payment-form" action="<?= Url::to(['payment/index']); ?>">
          <?php if ($errors) : ?>
          <section>
          Errors:<br>
          <?php foreach ($errors as $e) : ?>
          <p><?php echo $e->message; ?></p>
          <?php endforeach; ?>
          </section>
          <?php endif; ?>
          <section>
          <label for="amount">
          <span class="input-label">Amount</span>
          <div class="input-wrapper amount-wrapper">
          <input id="amount" name="amount" type="tel" min="1" placeholder="Amount" value="<?= $amount; ?>">
          </div>
          </label>
          <div class="bt-drop-in-wrapper">
          <div id="bt-dropin"></div>
          </div>
          </section>

          <button class="button" type="submit"><span>Test Transaction</span></button>
          </form>
          -->
         * 
         */ ?>
    <?php endif; ?>

    <h2>Refund</h2>
    <?= $this->render('_refund_form', ['model' => $refund]); ?>

    <h2>Your Transactions</h2>
    <?=
    \frontend\widgets\UserPayments::widget([
        'user' => Toolbox::currentUser(),
        'viewMode' => null, //Full data view mode
        'providerOptions' => [
            'pagination' => ['pageSize' => 9],
        ],
        'gridOptions' => [
            'layout' => '{items}{pager}',
            'ajaxUpdate' => true,
        ],
    ]);
    ?>    
</div>

frontend/views/payment/refund.php
<?php
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

frontend/views/payment/skrill.php
<?php
/*
  
// 
use zvook\Skrill\Models\QuickCheckout;
use zvook\Skrill\Forms\QuickCheckoutForm;

$quickCheckout = new QuickCheckout([
    'pay_to_email' => 'grayfolk@gmail.com',
    'amount' => 123,
    'currency' => 'EUR',
]);

$form = new QuickCheckoutForm($quickCheckout);

echo $form->open([
    'class' => 'skrill-form'
]);

$exclude = [];
echo $form->renderHidden($exclude);
//<input type="text" name="amount"> .....
echo $form->renderSubmit('Pay', ['class' => 'btn']);
echo $form->close();
 * 
 */
?>

<?php
$form = \yii\widgets\ActiveForm::begin([
    'id' => 'payment-form',
//	'action' => Yii::$app->skrill->actionUrl,
	'action' => \yii\helpers\Url::to(['payment/skrill-redirect']),
    'options' => [],
]) 
?>
<?= $model->renderHiddenFields(); ?>
 <?= yii\helpers\Html::submitButton(Yii::t('app', 'Process Payment'), ['class' => 'btn btn-green']); ?>
<?php \yii\widgets\ActiveForm::end() ?>