frontend/models/Advertiser.php
<?php


namespace frontend\models;

use Yii;
use common\models\User;
use common\models\Booking;
use frontend\models\Services;
use common\interfaces\IBookingParticipant;
use common\models\AdvertiserScore;
use frontend\models\LikePhoto;


/**
 * This is the model class for table "advetiser".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $title
 * @property integer $type
 * @property integer $price
 * @property string $date
 * @property integer $age
 * @property integer $height
 * @property integer $weight
 * @property integer $hair
 * @property integer $eye
 * @property integer $skin
 * @property integer $silicone
 * @property string $nationality
 * @property string $offering
 * @property string $receiving
 * @property string $desc
 * @property integer $online
 * @property string $payment_id
 * @property integer $sex_id
 *
 * @property User $user
 * @property AdvetiserImage[] $advetiserImages
 * @property AdvertiserScore $advertiserScores
 */
class Advertiser extends \yii\db\ActiveRecord implements IBookingParticipant
{

	// Non-standard scenarios
	const SC_SIGNUP = 'signup';
	const ONLINE_BASED_ON_BOOKING = 0;
	const ONLINE_MANUAL_ONLINE = 1;
	const ONLINE_MANUAL_OFFLINE = 2;

	/**
	 * @inheritdoc
	 */
	public $onlineStatus;
	public $receiving_as_value = array();
	public $offering_as_value = array();
	public $receiving_as_id = array();
	public $offering_as_id = array();
	public $services = array();
	public $phone;
	public $username;
	public $sexList = [];
	public $sexListTitle = [];


	public static function tableName()
	{
		return '{{%advertiser}}';
	}


	public function behaviors()
	{
		return [
			\common\behaviors\BookingParticipantBehavior::className(),
		];
	}


	/**
	 * @inheritdoc
	 */
	public function scenarios()
	{
		$scenarios = parent::scenarios();
		$scenarios[self::SC_SIGNUP] = [];
		return $scenarios;
	}


	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['user_id'], 'required'],
			[['user_id', 'height', 'weight', 'hair_id', 'eye_id', 'skin_id', 'silicone', 'online', 'nationality_id', 'cities_id', 'country_id', 'bra_id', 'shoe_size'], 'integer'],
			[['desc'], 'string'],
			[['age'], 'integer', 'min' => 18],
			[['title', 'date', 'offering', 'receiving', 'username'], 'string', 'max' => 255],
			[['payment_id'], 'string', 'max' => 25],
			[['price', 'phone'], 'safe']
		];
	}


	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User ID'),
			'title' => Yii::t('app', 'Title'),
			'price' => Yii::t('app', 'Price'),
			'date' => Yii::t('app', 'Date'),
			'age' => Yii::t('app', 'Age'),
			'height' => Yii::t('app', 'Height'),
			'weight' => Yii::t('app', 'Weight'),
			'hair_id' => Yii::t('app', 'Hair'),
			'eye_id' => Yii::t('app', 'Eye'),
			'skin_d' => Yii::t('app', 'Skin'),
			'silicone' => Yii::t('app', 'Silicone breasts'),
			'nationality_id' => Yii::t('app', 'Nationality'),
			'cities_id' => Yii::t('app', 'City'),
			'offering' => Yii::t('app', 'Offering'),
			'receiving' => Yii::t('app', 'Receiving'),
			'desc' => Yii::t('app', 'Desc'),
			'online' => Yii::t('app', 'Online'),
			'bra_id' => Yii::t('app', 'Bra size'),
			'shoe_size' => Yii::t('app', 'Shoe size'),
			'payment_id' => Yii::t('app', 'Payment ID'),
		];
	}


	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getUser()
	{
		return $this->hasOne(User::className(), ['id' => 'user_id']);
	}


	public function getCity()
	{
		return $this->hasOne(City::className(), ['id' => 'cities_id']);
	}


	public function getCountry()
	{
		return $this->hasOne(Country::className(), ['id' => 'country_id']);
	}


	public function getBra()
	{
		return $this->hasOne(Bra::className(), ['id' => 'bra_id']);
	}


	public function getHair()
	{
		return $this->hasOne(Colors::className(), ['id' => 'hair_id']);
	}


	public function getEye()
	{
		return $this->hasOne(Colors::className(), ['id' => 'eye_id']);
	}


	public function getSkin()
	{
		return $this->hasOne(Colors::className(), ['id' => 'skin_id']);
	}


	public function getNationality()
	{
		return $this->hasOne(Nationality::className(), ['id' => 'nationality_id']);
	}


	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getImages()
	{
		return $this->hasMany(AdvertiserImage::className(), ['id_advertiser' => 'id']);
	}


	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getAdvertiserScores()
	{
		return $this->hasOne(AdvertiserScore::className(), ['advertiser_id' => 'id']);
	}


	/**
	 * Shortcut to getAdvertiserScores with NULL checking
	 * 
	 * @return int
	 */
	public function getPoints()
	{
		return ((boolean) $this->advertiserScores) ? $this->advertiserScores->amount_sum : 0;
	}


	public function getBookingRequests()
	{
		return $this->hasMany(BookingRequests::className(), ['advertiser_id' => 'id']);
	}


	/**
	 * @inheritdoc
	 * @return AdvetiserQuery the active query used by this AR class.
	 */
	public static function find()
	{
		return new AdvertiserQuery(get_called_class());
	}


	public function afterFind()
	{
		if ($this->isOnlineManual()) {
			$this->onlineStatus = ($this->online == self::ONLINE_MANUAL_OFFLINE ? 'offline' : 'online');
		} elseif (($this->user->time_session + 310) > time()) {
			$this->onlineStatus = 'online';
		} else {
			$this->onlineStatus = 'offline';
		}
		$this->loadServices();
		$this->phone = $this->user->phone;
		$this->username = $this->user->username;

		$this->receiving();
		$this->offering();
	}


	public function loadServices()
	{
		if (empty($this->services)) {
			$this->services = $this->refactorArrayModel(Services::find()->asArray()->all());
		}
	}


	public static function refactorArrayModel($model)
	{
		$rez = array();
		foreach ($model as $value) {
			$rez[$value['id']] = $value['title'];
		}
		return $rez;
	}


	public function receiving()
	{
		if (!empty($this->receiving)) {
			$arr = explode(',', $this->receiving);
			array_shift($arr);
			array_pop($arr);
			foreach ($arr as $value) {
				if (isset($this->services[$value])) {
					$this->receiving_as_value[] = $this->services[$value];
					$this->receiving_as_id[] = $value;
				}
			}
			return true;
		} else {
			return false;
		}
	}


	public function offering()
	{
		if (!empty($this->offering)) {
			$arr = explode(',', $this->offering);
			array_shift($arr);
			array_pop($arr);
			foreach ($arr as $value) {
				if (isset($this->services[$value])) {
					$this->offering_as_value[] = $this->services[$value];
					$this->offering_as_id[] = $value;
				}
			}
			return true;
		} else
			return false;
	}


	/**
	 *
	 * @return ActiveQuery
	 */
	public function getBookings()
	{
		return $this->hasMany(Booking::className(), ['advertiser_id' => 'id']);
	}


	/**
	 *
	 * @return ActiveQuery
	 */
	public function getSex()
	{
		return $this->hasOne(Sex::className(), ['id' => 'sex_id']);
	}


	public function afterSave($insert, $changedAttributes)
	{
		parent::afterSave($insert, $changedAttributes);
		if ($insert || array_key_exists('age', $changedAttributes)) {
			$user = $this->user;
			$user->status = $this->age >= 18 ? User::STATUS_ACTIVE : User::STATUS_AGE_BLOCKED;
			if (!$user->save()) {
				print_r($user->errors);
			}
		}
	}


	public function getPause()
	{
		return $this->user->status == User::STATUS_PAUSE;
	}


	public function setPause($pauseState)
	{
		if ($pauseState) {
			$this->user->status = User::STATUS_PAUSE;
		} else {
			$this->user->status = ($this->age >= 18 ? User::STATUS_ACTIVE : User::STATUS_AGE_BLOCKED);
		}
		$this->user->save();
	}


	public function isOnlineBasedOnBooking()
	{
		return $this->online == self::ONLINE_BASED_ON_BOOKING;
	}


	public function isOnlineManual()
	{
		return $this->online == self::ONLINE_MANUAL_ONLINE || $this->online == self::ONLINE_MANUAL_OFFLINE;
	}


	public function isFavorit($user_id)
	{
		return Favorits::find()->where(['user_id' => $user_id])->andWhere(['advertiser_id' => $this->id])->count() > 0;
	}

	
	

	public function getLikeCountFromUser($id)
	{
		$query = $this->user->getMedia();
		$lp = LikePhoto::tableName();
		$am = AdvertiserMedia::tableName();
		$query
			->leftJoin($lp, $lp.'.media_id='.$am.'.id AND '.$lp.'.user_id=:likerId', [':likerId' => $id])
			->andWhere(['not',[$lp.'.id' => null]]);
		return $query->count();
	}
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use backend\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/views/site/advertiser/chat.php
<?php
/**
 * Created by PhpStorm.
 * User: Ievgen
 * Date: 04.07.2016
 * Time: 21:03
 */

use yii\widgets\Pjax;
use yii\helpers\Html;
use yii\web\View;
?>
<?php
$script = <<< JS
    var isAskUpdate = false;
    function tryUpdateHistory() {
      if (isAskUpdate) {
          return;
      }
      isAskUpdate = true;
      $("#linkToClick").click();
    }
    setInterval(tryUpdateHistory, 6000);
    $(document).on("pjax:success", function() {
        if (isAskUpdate) {
          isAskUpdate = false;
        } else {
          tryUpdateHistory();
        }
    });
JS;
$this->registerJs($script, View::POS_READY);
?>

<div style="position:absolute;left:0;top:-9999px;">
    <div class="pop-up pop-chat" id="pop-chat">
        <div class="pop-title"><?= $template['title']?></div>
        <div class="revs scroll">
            <?php Pjax::begin(); ?>
            <?php if ($chat) {
                foreach($chat->messages as $value): ?>
                <div class="rev">
                    <div class="rev-name"><?= $value->sender ?></div>
                    <div class="rev-txt"><?= $value->content ?></div>
                </div>
            <?php endforeach;
            } ?>
            <?= Html::a("update", ['site/advertiser', 'id'=>$model->id], ['id' =>'linkToClick', 'class'=>'btn-choose','style'=>'display:none;']);?>
            <?php Pjax::end(); ?>
        </div>
        <?php Pjax::begin(); ?>
        <?= Html::beginForm(['site/advertiser', 'id'=>$model->id], 'post', ['data-pjax' => '', 'class' => 'form-inline']); ?>
        <?= Html::textarea('content',$message->content)?>
        <?= Html::submitButton(Yii::t('app','Submit'), ['class' => 'btn', 'name' => 'chat-button', 'id'=>'refreshButton']) ?>
        <?= Html::endForm() ?>
        <?php Pjax::end(); ?>
    </div>
</div>

frontend/views/site/advertiser/profile.php
<?php

/**
 * Created by PhpStorm.
 * User: Ievgen
 * Date: 17.05.2016
 * Time: 1:38
 */
use yii\helpers\Html;
use frontend\widgets\ReviewsBar;
use common\assets\FullCalendarAsset;
use yii\web\View;

FullCalendarAsset::register($this);

$isNadv = \Yii::$app->user->can('nonAdvetiserProfile');
?>

<div class="user-cont girl-view">
    <div class="user-col">

        <div class="girl-profile">
            <div class="fields-top">
                <div class="field-name">
                <?php if ($isNadv) { ?>
                   <span class="fav-star<?= ($model->isFavorit(\Yii::$app->user->getId()) ? ' on"' : '" title="' . Yii::t('app', 'Add to favorites') . '"'); ?>></span>
                 <?php } ?>
                  <?= $model->user->username ?>
                </div>
                <?php if ($isNadv || \Yii::$app->user->getId() == $model->user_id) { ?>
                  <a href="<?= \common\helpers\Calendar::url($model); ?>" class="link-datepicker fancy"><span><?= Yii::t('app', 'Calendar'); ?></span></a>
                <?php } ?>
                <div class="field-points">
                  <?php echo Yii::t('app', '{scores} points', ['scores' => $model->points]); ?>
                </div>
          </div>
          <div class="field-short">“<?= $model->title ?>”</div>
          <div class="prof-cols">
					<div class="col-photos">
						<div class="main-photo">
							<?php if (count($all_photos) > 0) { ?>
								<img src="<?= $default_photo ? $default_photo['big_url'] : ''; ?>" alt=""  class="gal" data-index="<?= $default_photo_index; ?>">
							<?php } else { ?>
                <div class="lightgrey-border">
                <span class="no-photo-block"><?=\Yii::t('app', 'Nо photo uploaded');?></span>
              </div>
              <?php } ?>
						</div>
						<div class="thumbs">
							<?php
							$org_hrefs = array();
							foreach ($all_photos as $i => $photo) {
								$org_hrefs[] = $photo['org_url'];
								?>
								<div class="thumb">
									<img src="<?= $photo['small_url']; ?>" alt="" class="gal" data-index="<?= $i; ?>">
								</div>
								<?php
							}
							?>
						</div>
					</div>
					<div class="col-sett">
						<div class="field-place">
							<?= Yii::t('app', 'Available now in {city}', ['city' => '<a href="#">' . ($model->city ? $model->city->title : '') . '</a>']); ?>
						</div>
						<div class="filter-block">
							<div class="filter-label"><?= Yii::t('app', 'Price'); ?>
								<div class="filter-value"><?= $model->price ?> €/h</div>
							</div>
						</div>
						<div class="filter-block">
							<div class="filter-label"><?= Yii::t('app', 'Age'); ?>
								<div class="filter-value"><?= $model->age ?> <?= Yii::t('app', 'y.o.'); ?></div>
							</div>
						</div>
						<div class="filter-block">
							<div class="filter-label">
								<?= Yii::t('app', 'Sex'); ?>
								<div class="filter-value"><?= $model->sex ? $model->sex->title : ''; ?></div>
							</div>
						</div>
						<div class="filter-block active">
							<div class="filter-label filter-opener"><?= Yii::t('app', 'Appearance'); ?></div>
							<div class="filter-drop">
								<div class="f-row">
									<label><?= Yii::t('app', 'Height'); ?></label>
									<div class="filter-value"><?= $model->height ?> <?= Yii::t('app', 'cm'); ?></div>
								</div>
								<div class="f-row">
									<label><?= Yii::t('app', 'Weight'); ?></label>
									<div class="filter-value"><?= $model->weight ?> <?= Yii::t('app', 'kg'); ?></div>
								</div>
								<div class="f-row">
									<label><?= Yii::t('app', 'Hair color'); ?></label>
									<div class="filter-value">
										<span class="noedit color <?= !empty($model->hair) ? $model->hair->class : '' ?>"></span><?= !empty($model->hair) ? Yii::t('app', $model->hair->title) : ''; ?>
									</div>
								</div>
								<div class="f-row">
									<label><?= Yii::t('app', 'Eye color'); ?></label>
									<div class="filter-value">
										<span class="noedit color <?= !empty($model->eye) ? $model->eye->class : '' ?>"></span><?= !empty($model->eye) ? Yii::t('app', $model->eye->title) : ''; ?>
									</div>
								</div>
								<div class="f-row">
									<label><?= Yii::t('app', 'Skin color'); ?></label>
									<div class="filter-value">
										<span class="noedit color <?= !empty($model->skin) ? $model->skin->class : '' ?>"></span><?= !empty($model->skin) ? Yii::t('app', $model->skin->title) : ''; ?>
									</div>
								</div>
								<div class="f-row">
									<label><?= Yii::t('app', 'Shoe size'); ?></label>
									<div class="filter-value">
										<?= $model->shoe_size ?>
									</div>
								</div>
								<div class="f-row">
									<label><?= Yii::t('app', 'Bra size'); ?></label>
									<div class="filter-value">
										<?= !empty($model->bra) ? $model->bra->title : '' ?>
									</div>
								</div>
								<div class="f-row">
									<div class="check">
											<?= Html::checkbox('silicone', $model->silicone, ['disabled' => 'disabled']) ?>
											<span class="f-text"><?= Yii::t('app', 'Silicone breasts') ?></span>
									</div>
								</div>

							</div>
						</div>
						<div class="filter-block">
							<div class="filter-label"><?= Yii::t('app', 'Nationality'); ?>
								<div class="filter-value"><?= !empty($model->nationality) ? Yii::t('app', $model->nationality->title) : ''; ?></div>
							</div>
						</div>
						<div class="filter-block">
							<div class="filter-label filter-opener"><?= Yii::t('app', 'Services offering'); ?></div>
							<div class="filter-drop white">
								<?= $this->render('tags', ['models' => $model->offering_as_value]) ?>
							</div>
						</div>
						<div class="filter-block">
							<div class="filter-label filter-opener"><?= Yii::t('app', 'Services receiving'); ?></div>
							<div class="filter-drop white">
								<?= $this->render('tags', ['models' => $model->receiving_as_value]) ?>
							</div>
						</div>
						<div class="filter-block">
							<?=
							ReviewsBar::widget([
								'id' => $model->user->id,
								'action' => 'advertiser',
								'reply' => false
							])
							?>
						</div>

					</div>
				</div>
				<div class="field-desc">
					<p><?= $model->desc ?></p>
				</div>
				<div class="sett-subm">
          <?php if (\Yii::$app->getUser()->id) { ?>
					<?= $template['bookingRequest'] ?>
					<?= $template['chat'] ?>
					<?= $this->render('/site/pop_up/pop_report_spam', ['model' => $model]); ?>
          <?php } else { ?>
          <span class="color-red"><?=\Yii::t('app', 'Please, register to make a booking');?></span>
          <?php } ?>
				</div>
			</div>
		</div>
	</div>
	<div>
		<?= $this->render('chat', ['model' => $model, 'chat' => $chat, 'template' => $template, 'message' => $message]); ?>
	</div>
	<div style="display:none;">
		<?= $this->render('/site/pop_up/pop_book_req', ['model' => $model]) ?>
		<?=
		$this->render('/site/pop_up/_pop_booking', [
			'template' => $template,
			'model' => $model,
		]);
		?>
		<?= $this->render('/site/pop_up/pop_book', ['template' => $template]) ?>
	</div>
	<?php
	$js = '
  $(".gal").click(function() {
    $.fancybox(
      ["' . implode("\",\n\"", $org_hrefs) . '"],
      {
        "type": "image",
        "index": $(this).attr("data-index"),
        "arrows" : false,
        "afterLoad": function () {
            setTimeout(checkLike, 500);
         },
        "tpl": {
          "image": "<img class=\"fancybox-image\" src=\"{href}\" alt=\"\">' . ($isNadv ? '<a href=\"#\" class=\"link-like\" onClick=\"likePhoto(this, $(\'.fancybox-image\').attr(\'src\'))\" title=\"' . Yii::t('app', 'Like this photo') . '\"></a>' : '') . '",
         }
      }
    );
  });

  $(".fav-star").click(function() {
    $(this).toggleClass("on");
    $.post(
      "' . Yii::getAlias('@frontendWeb') . '/site/change-favorit",
      {"adv":' . $model->id . '},
      function() { location.reload(); }
    );
  });
  ';
	$this->registerJs($js, View::POS_READY);

	$js = '
  var checkIsLiked = {};
  var imgId = ' . json_encode($imgId) . ';

  function likePhoto(likeIcon, imageUrl)
  {
	if (!$(likeIcon).hasClass("liked") && !$(likeIcon).hasClass("disabled")) {
    $.post(
      "' . Yii::getAlias('@frontendWeb') . '/site/like-photo",
      {"id":imgId[imageUrl]},
	  function () {
	    checkIsLiked[imageUrl] = true;
		$(likeIcon).toggleClass("liked");
	  }
    );
	}
  }

  function checkLike()
  {
    var url = $(".fancybox-image").attr("src");
    if (checkIsLiked.hasOwnProperty(url) && checkIsLiked[url]) {
      $(".link-like").addClass("liked");
      return;
    }
    $.post(
      "' . Yii::getAlias('@frontendWeb') . '/site/is-liked-photo",
      {"url":url},
      function (data) {
		data = parseInt(data);
        if (data) {
          checkIsLiked[url] = (data == 1 || data == 3);
        }
        if (checkIsLiked.hasOwnProperty(url) && checkIsLiked[url]) {
          $(".link-like").addClass("liked");
        }

		if (data == 2 || data == 3) {
          $(".link-like").addClass("disabled");
		}

      }
    );
  }
  ';
	$this->registerJs($js, View::POS_END);

frontend/views/site/advertiser/tags.php
<?php
/**
 * Created by PhpStorm.
 * User: Ievgen
 * Date: 07.06.2016
 * Time: 19:22
 */

use yii\helpers\Html;
?>
<div class="tags">
    <?php
        foreach($models as $value)
        {
            echo '<span class="select2-selection__choice">',Yii::t('app', $value),'</span>';
        }
    ?>
</div>

frontend/views/site/advertiser/view.php
<?php

/**
 * Created by PhpStorm.
 * User: Ievgen
 * Date: 09.05.2016
 * Time: 13:44
 */
use common\assets\FullCalendarAsset;

FullCalendarAsset::register($this);
?>
<div class="girl offline"><a href="--><?//= \yii\helpers\Url::toRoute('site/advertiser');?><!--" class="cover-link"></a>
    <div class="girl-img"><img src="images/img10.jpg" alt=""/></div>
    <div class="girl-cont">
        <div class="girl-name">Anna, 25</div>
        <div class="girl-price"><b>25</b> €/h</div>
        <div class="girl-txt">I am a hot blonde;) willing to make your dreams come true.</div>
    </div>
</div>