frontend/controllers/NonAdvertiserController.php
<?php


namespace frontend\controllers;

use yii;
use frontend\models\BookingRequests;
use frontend\models\Reviews;
use frontend\models\Replys;
use frontend\models\PaymentsList;
use common\models\User;
use common\helpers\Toolbox;
use yii\helpers\Html;
use yii\web\NotFoundHttpException;
use yii\web\HttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;


class NonAdvertiserController extends \yii\web\Controller
{

	public $layout = 'nonadvertiser';
	protected $template = array();


	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['non-advertiser-profile', 'review', 'reply', 'index', 'booking'],
						'allow' => true,
						'roles' => ['NON Advetiser'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['post'],
				],
			],
		];
	}


	public function actions()
	{
		return [
			'history' => \frontend\actions\BookingHistoryAction::className(),
			'booking' => [
				'class' => \frontend\actions\AdvertiserCalendarAction::className(),
				'view' => '@frontend/views/non-advertiser/calendar',
			],
		];
	}


	public function actionIndex()
	{
		$model = Toolbox::currentNonAdvertiser();

		if (!$model) {
			throw new HttpException(403, 'Access Denied.');
		}

		return $this->render('profile', [
				'model' => $model,
		]);
	}


	public function actionNonAdvertiserProfile($id = null)
	{

		/*
		  if ($model = BookingRequests::loadModel2User(Yii::$app->getUser()->id)) {
		  $this->message(BookingRequests::checkAlert($model));
		  }
		 *
		 */
		if ($id) {
			$user = $model = $this->findModel($id);
		} else {
			$user = $model = Toolbox::currentNonAdvertiser();
		}

		if (isset($_POST['hasEditable'])) {
			\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;


			if (isset(Yii::$app->request->post()['NonAdvertiser']['phone'])) {
				$user->phone = trim(Yii::$app->request->post()['NonAdvertiser']['phone'], "\x00..\x1F");
				$value = $user->phone;
				if ($user->save())
					return ['output' => $value, 'message' => ''];
				else
					return ['output' => '', 'message' => 'Not valid'];
			}


			// else if nothing to do always return an empty JSON encoded output
			else {
				return ['output' => 'Non save', 'message' => ''];
			}
		}
		$payments = PaymentsList::findAll(['enabled_for_payment' => 1]);

		return $this->render('profile', [
				'model' => $model,
				'user' => $user,
				'payments' => $payments,
				'isOwn' => true
		]);
	}


	public function actionReview($id)
	{

		$this->layout = false;
		$model = new Reviews();

		if ($user = $this->findModel($id)) {
			if (Yii::$app->request->isPost) {

				if ($model->load(Yii::$app->request->post())) {

					$model->id_to = $id;
					$model->id_from = Yii::$app->getUser()->id;
					$model->date_add = time();
					if ($model->save())
						$this->redirect('non-advertiser-profile');
				}
			}
			$this->template['title'] = Yii::t('app', 'Write a review');
			$this->template['data'] = Html::a($user->username, '#') . ' 12 Dec-22 Dec ';
			$this->template['label'] = Yii::t('app', 'Review text:');
			$this->template['textarea'] = Html::activeTextarea($model, 'title');
			$this->template['submit'] = Html::submitButton(Yii::t('app', 'Post the review'), ['name' => 'submit-review', 'class' => 'btn']);

			if (Yii::$app->request->isAjax) {
				return $this->render('review', ['template' => $this->template]);
			}

			$this->redirect('non-advertiser-profile');
		} else {
			throw new NotFoundHttpException('User with id=' . $id . ' not found');
		}
	}


	public function actionReply($id)
	{

		$this->layout = false;
		$model = $this->findReviewsModel($id);
		$reply = new Replys();

		if (Yii::$app->request->isPost) {

			if ($reply->load(Yii::$app->request->post())) {
				$reply->id_review = $id;
				$reply->id_from = Yii::$app->getUser()->id;
				$reply->date_add = time();
				$reply->save();
			}
		}
		$this->template['title'] = Yii::t('app', 'Write a reply');
		$this->template['data'] = Html::a($model->idfrom->username, '#') . ' 12 Dec-22 Dec ';
		$this->template['label'] = Yii::t('app', 'Reply text:');
		$this->template['textarea'] = Html::activeTextarea($reply, 'title');
		$this->template['submit'] = Html::submitButton(Yii::t('app', 'Post the reply'), ['name' => 'submit-reply', 'class' => 'btn']);

		if (Yii::$app->request->isAjax)
			return $this->render('review', ['template' => $this->template]);

		$this->redirect('non-advertiser-profile');
	}


	protected function message($models)
	{
		if (!empty($models)) {
			foreach ($models as $key => $model) {
				Yii::$app->getSession()->setFlash('confirm' . $key, [
					'direction' => 'confirm booking request',
					'title' => Yii::t('app', 'Congratulations, {username}! Your booking request has been confirmed by {username2}', ['username' => $model->nonadvertiser->username, 'username2' => $model->advertiser->user->username]),
					'text' => '&nbsp;',
				]);

				Yii::$app->getSession()->setFlash('booking' . $key, [
					'direction' => 'confirm booking request',
					'title' => Yii::t('app', 'You just confirmed booking request <br/>from {username}', ['username' => $model->advertiser->user->username]),
					'text' => 'Date: 12.09.2016, Time: 12:00 - 16:00',
				]);
				$model->alert = BookingRequests::ALERT_DONE;
				$model->save();
			}
		}
	}


	protected function findModel($id)
	{
		if (($model = User::findOne($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}


	protected static function findReviewsModel($id)
	{
		if (($model = Reviews::findOne($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}


	/*
	  protected function findUserModel()
	  {
	  if (($model = User::findOne(Yii::$app->getUser()->id)) !== null) {
	  return $model;
	  } else {
	  return false;
	  }
	  }
	 *
	 */

}

frontend/views/non-advertiser/booking_item.php
<?php
/**
 * Created by PhpStorm.
 * User: Ievgen
 * Date: 31.05.2016
 * Time: 0:44
 */

use yii\helpers\Html;
?>
<div class="girl <?= $model->advertiser->onlineStatus ?>"><?= Html::a('',['site/advertiser', 'id'=>$model->advertiser->id],['class'=>'cover-link'])?>
    <div class="girl-img"><?= Html::img(Yii::getAlias('@frontendImages/advertiser/220x220/').$model->advertiser->images[0]->getHash().'.jpg', ['alt' => $model->advertiser->images[0]->title]) ?></div>
    <div class="girl-cont">
        <div class="girl-name"><?= $model->advertiser->user->username ?>, <?= $model->advertiser->age ?></div>
        <div class="girl-price"><b><?= $model->advertiser->price ?></b> €/h</div>
        <div class="girl-txt"><?= $model->advertiser->title ?>.</div>
    </div>
    <div class="bot-inf">
        <div class="date">19 Jan - 23 Jan 2015</div>
        <?= Html::a(Yii::t('app','Write a review'),['non-advertiser/review', 'id'=>$model->advertiser->user->id],['class'=>'fancy fancybox.ajax']); ?>
    </div>
</div>

frontend/views/non-advertiser/calendar.php
<?php

/**
 * Created by PhpStorm.
 * User: Ievgen
 * Date: 29.04.2016
 * Time: 13:24
 */
use yii\helpers\Html;
use frontend\widgets\ReviewsBar;
use frontend\widgets\AdvInfo;
use yii\web\View;
use common\assets\ProjectAsset;
use yii\helpers\Url;
use common\helpers\Toolbox;

ProjectAsset::register($this);
?>

<?php
echo \frontend\widgets\NonAdvInfo::widget([
	'user' => Toolbox::currentNonAdvertiser(),
])
?>


<div class="girl-profile">
	<div class="fields-top">
		<div class="field-name"><?= $model->user->username ?></div>
	</div>

	<div id="calendar"></div>
</div>

<?php $this->registerJs("project.booking.initCalendar({
	events: '" . Url::toRoute(['booking/feed', 'id' => $model->id]) . "',
	bookingUrl: '" . Url::toRoute(['booking/book', 'id' => $model->id, 'cid'=>  Toolbox::currentUser()->id]) . "',
});"); ?>

frontend/views/non-advertiser/index.php
<?php
/* @var $this yii\web\View */
?>
<h1>non-advetiser/index</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

frontend/views/non-advertiser/profile.php
<?php

/**
 * Created by PhpStorm.
 * User: Ievgen
 * Date: 06.05.2016
 * Time: 21:07
 */
use frontend\widgets\ReviewsBar;
use frontend\widgets\NonAdvInfo;
use yii\web\View;
use common\models\Transaction;


$this->registerJsFile(Yii::getAlias('@frontendWeb') . '/js/jquery.editable.js', ['depends' => [\yii\web\JqueryAsset::className()]]);

$this->registerJs('$(".editable").editable("' . \Yii::$app->request->csrfToken . '", "NonAdvertiser");', View::POS_READY);
?>
<div class="user-col">
    <?=
    NonAdvInfo::widget([
        'user' => $model,
        'payments' => $payments
    ]);
    ?>

    <div class="reviews-col">
        <?=
        \frontend\widgets\ReviewsBar::widget([
            'id' => $model->id
        ])
        ?>
        <div class="acc-title opener"><?= Yii::t('booking', 'Transactions'); ?><sup>(<?= Transaction::find()->byUser($model)->count() ?>)</sup></div>
        <div class="acc-drop">
            <div class="revs scroll">
                <?=
                \frontend\widgets\UserPayments::widget([
                    'user' => $model,
                    'viewMode' => 'short',
                    'providerOptions' => [
                        'pagination' => ['pageSize' => 9],
                    ],
                    'gridOptions' => [
                        'layout' => '{items}',
                    ],
                ]);
                ?>
            </div>
        </div>            
    </div>
</div>
<div class="booking-col">
<?php if ($isOwn) { ?>
        <div class="col-top"></div>
        <div class="acc-title opener <?= $model->bookingActiveCount ? 'active' : '' ?>"><?= Yii::t('app', 'Active Bookings'); ?><sup>(<?= $model->bookingActiveCount; ?>)</sup></div>
        <div class="acc-drop <?= $model->bookingActiveCount ? 'active' : '' ?>">
            <div class="scroll">
                <?php
                echo \common\widgets\NonAdvBookingList::widget([
                    'query' => $model->getBookingActiveQuery(),
                    'isPastBooking' => true
                ]);
                ?>
            </div>
        </div>

        <div class="acc-title opener <?= $model->bookingPendingCount ? 'active' : '' ?>"><?= Yii::t('app', 'Pending Requests'); ?><sup>(<?= $model->bookingPendingCount; ?>)</sup></div>
        <div class="acc-drop <?= $model->bookingPendingCount ? 'active' : '' ?>">
            <div class="scroll">
                <?php
                echo \common\widgets\NonAdvBookingList::widget([
                    'query' => $model->getBookingPendingQuery(),
                ]);
                ?>
            </div>
        </div>

        <div class="acc-title opener <?= $model->bookingPastCount ? 'active' : '' ?>"><?= Yii::t('app', 'Past Bookings'); ?><sup>(<?= $model->bookingPastCount; ?>)</sup></div>
        <div class="acc-drop">
            <div class="scroll">
                <div class="girls">
                    <?php
                    echo \common\widgets\NonAdvBookingList::widget([
                        'query' => $model->getBookingPastQuery(),
                        'limit' => false,
                        'showMoreLink' => false,
                        'isPastBooking' => true
                    ]);
                    ?>
                </div>
            </div>
        </div>
<?php } ?>
</div>

<?= $this->render('//site/pop_up/pop_booking_list') ?>

frontend/views/non-advertiser/review.php
<?php
/**
 * Created by PhpStorm.
 * User: Ievgen
 * Date: 11.06.2016
 * Time: 3:23
 */

use yii\bootstrap\ActiveForm;
?>

<div class="pop-up" id="pop-reply">
    <div class="pop-title title-mess"><?= $template['title']?></div>
    <div class="mess-data"><?= $template['data']?></div>
    <?php $form = ActiveForm::begin(['id' => 'form-reply']); ?>
    <div class="mess-form">
        <label><?= $template['label']?></label>
        <?= $template['textarea']?>
    </div>
    <div class="mess-submit">
        <a href="#" class="btn btn-gray" onclick="$.fancybox.close();"><?=Yii::t('app', 'Cancel');?></a>
        <?= $template['submit']?>
    </div>
    <?php ActiveForm::end(); ?>
</div>