backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use backend\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;


use Yii;
use common\models\User;
use common\models\LoginForm;
use backend\models\Pages;
use backend\models\Settings;
use yii\helpers\Html;
use yii\helpers\VarDumper;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\Advertiser;
use frontend\models\AdvertiserSearch;
use frontend\models\AdvertiserMedia;
use frontend\models\BookingRequests;
use frontend\models\Services;
use frontend\models\Chat;
use frontend\models\Message;
use frontend\models\City;
use frontend\models\Favorits;
use frontend\models\SpamReport;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Controller;
use yii\web\HttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
use common\helpers\Toolbox;
use common\helpers\Scoring;
use common\models\Score;
use common\models\ScoreQuery;


/**
 * Site controller
 */
class SiteController extends Controller
{

    protected $template = array();



    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        Yii::$app->params['filter'] = 0;

        return parent::beforeAction($action);
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'email'],
                'rules' => [
                    [
                        'actions' => ['signup', 'email'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'email'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
//                    'logout' => ['post'],
                ],
            ],
        ];
    }


    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
//            'error' => [
//                'class' => 'yii\web\ErrorAction',
//            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'calendar' => \frontend\actions\AdvertiserCalendarAction::className(),
        ];
    }


    /**
     * Displays custom error page
     *
     * @inheritdoc
     */
    public function actionError()
    {
        return $this->render('error');
    }


    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AdvertiserSearch();

        if ($searchModel->load(Yii::$app->request->get())) {
            Yii::$app->params['filter'] = $searchModel;
        }
        $pages = false;
        $dataProvider = new ActiveDataProvider([
            'query' => $searchModel->search(Yii::$app->request->queryParams)->query->orderByScores(),
            'pagination' => array('pageSize' => AdvertiserSearch::ITEMS_PER_PAGE),
        ]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    /* Old
      public function actionLogin()
      {
      if (!\Yii::$app->user->isGuest) {
      return $this->goHome();
      }
      $model = new LoginForm();
      if ($model->load(Yii::$app->request->post()) && $model->login()) {
      return $this->goBack();
      } else
      return $this->render('login', [
      'model' => $model,
      ]);
      }
     *
     */


    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        $serviceName = Yii::$app->getRequest()->getQueryParam('service');
        if (isset($serviceName)) {
            /** @var $eauth \nodge\eauth\ServiceBase */
            $eauth = Yii::$app->get('eauth')->getIdentity($serviceName);
            $eauth->setRedirectUrl(Yii::$app->getUser()->getReturnUrl());
            $eauth->setCancelUrl(Yii::$app->getUrlManager()->createAbsoluteUrl('site/login'));

            try {
                if ($eauth->authenticate()) {
                    ///var_dump($eauth->getIsAuthenticated(), $eauth->getAttributes()); exit;
                    $identity = User::findByEAuth($eauth);
                    Yii::$app->getUser()->login($identity);

                    // special redirect with closing popup window
                    $eauth->redirect();
                } else {
                    // close popup window and redirect to cancelUrl
                    $eauth->cancel();
                }
            } catch (\nodge\eauth\ErrorException $e) {
                // save error to show it later
                Yii::$app->getSession()->setFlash('error', 'EAuthException: ' . $e->getMessage());

                // close popup window and redirect to cancelUrl
                //				$eauth->cancel();
                $eauth->redirect($eauth->getCancelUrl());
            }
        }

        $model = new LoginForm();
        if ($model->load($_POST) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', array(
                'model' => $model,
            ));
        }
    }


    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Settings::find()->one()->admin_email)) {
                \Yii::$app->session->setFlash('success', 'Your message was sent! Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                \Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }


    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }


    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {

        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                // if (Yii::$app->getUser()->login($user)) {
                return $this->goHome();
                // }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }


    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }


    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }


    public function actionPage($id)
    {
        $model = Pages::findOne(['title' => $id, 'status' => 1]);
        if (is_null($model)) {
            throw new HttpException(404, 'Page not found');
        }
        return $this->render('page', [
            'model' => $model,
        ]);
    }


    public function actionAdvertiser($id)
    {

        $this->layout = 'site';

        $model = $this->findModel($id);
        if (empty($model->user)) {
            throw new HttpException(404, 'Page not found');
        }

        /* ---Chat--- */

        $chat = $this->findChatModel($model->user->id, Yii::$app->request->post() && Yii::$app->request->post('content'));
        $message = new Message();
        if ($chat) {
            if (Yii::$app->request->isPost) {

                $message->chat_id = $chat->id;
                $message->user_id = Yii::$app->getUser()->id;
                $message->content = Yii::$app->request->post('content');
                $message->created_at = time();
                $message->save();
            }
            $message->content = '';
            // $this->template['chat'] = Html::a(Yii::t('app', 'Start chat'), '#pop-chat', ['class' => 'link-chat f-right fancy']);

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <div class="flash" onclick="$(this).empty()">
        <?php if(Yii::$app->session->getFlash('success')): ?>
            <div id="w1-success" class="alert-success alert fade in" >
                <i class="icon fa fa-check"></i><?= Yii::$app->session->getFlash('success'); ?>
            </div>
        <?php endif; ?>
    </div>
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5 contact-form-container">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name') ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary contact-submit-button', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/email.php
<?php
/**
 * Created by PhpStorm.
 * User: angelus
 * Date: 31.03.2016
 * Time: 16:46
 */
?>
<div class="flash">
<?php if(Yii::$app->session->getFlash('success')): ?>
    <div id="w1-success" class="alert-success alert fade in" style="width: 350px; cursor: pointer" onclick="$('.flash').empty()">
        <i class="icon fa fa-check"></i><?= Yii::$app->session->getFlash('success'); ?>
    </div>
<?php endif; ?>
</div>
<div style="margin-left: 15px; width:350px; margin-top: 5px;">
    <form method="post">
        <label for="toEmail">TO:</label> <br />
        <input id="toEmail" name="toEmail" value="" /> <br />
        <label for="subject">Subject:</label><br />
        <input id="subject" name="subject" value="" /><br />
        <label for="msg">Message:</label>
        <textarea name="msg" id="msg" ></textarea>
        <input type="submit" name="submit" value="Send messsage" style="float: right; margin-top: 5px  "/>
    </form>
</div>

frontend/views/site/email_confirmed.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = \Yii::t('app', 'Confirm email');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p class="big-text"><?=Yii::t('app', $isOk ? 'Email has been confirmed. Now you can login.' : 'Email has not been confirmed. You can\'t login.');?></p>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = 'Oops!';
?>
<div id="content">
    <div class="cont-in">
        <div class="page404">
            <div class="title404"><?= \yii::t('app', 'Sorry. There is no such page on our website'); ?>.</div>
            <img src="<?= \yii::getAlias('@web'); ?>/images/img11.jpg" alt="" />
        </div>
    </div>
</div>

frontend/views/site/index.php
<?php

use \yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\LinkPager;
use frontend\widgets\InfiniteView;

/* @var $this yii\web\View */
/* @var $advertisers yii\web\User */

$this->title = 'Xclusivo - home page';
?>
<?php /*<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div> */ ?>
<div class="girls">
    <?= InfiniteView::widget([
        'dataProvider' => $dataProvider,
      //  'itemOptions' => ['class'=>'girl'],
      //  'layout' => "{items}",
      //  'itemView' => 'advetiser/view',
    ]);
?>
</div>
<?php
echo LinkPager::widget([
    'pagination' => $dataProvider->pagination
]);
?>


    <!--                <div class="girl offline"><a href="--><?//= \yii\helpers\Url::toRoute('site/advertiser');?><!--" class="cover-link"></a>-->
    <!--                    <div class="girl-img"><img src="/images/img10.jpg" alt=""/></div>-->
    <!--                    <div class="girl-cont">-->
    <!--                        <div class="girl-name">Anna, 25</div>-->
    <!--                        <div class="girl-price"><b>25</b> €/h</div>-->
    <!--                        <div class="girl-txt">I am a hot blonde;) willing to make your dreams come true.</div>-->
    <!--                    </div>-->
    <!--                </div>-->

<!--            <div class="btns"><a href="#" class="btn" onclick="alert('Coming Soon...')">Show me more</a></div>-->

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = \Yii::t('app', 'Login');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?=\Yii::t('app', 'Please fill out the following fields to login');?>:</p>

    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    <?=\Yii::t('app', 'If you forgot your password you can');?> <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton(\Yii::t('app', 'Login'), ['class' => 'btn btn-grey', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/page.php
<?php
/**
 * Created by PhpStorm.
 * User: angelus
 * Date: 23.02.2016
 * Time: 3:53
 */
$this->title = 'Xclusivo - ' . $model->meta_title;
?>
<div id="content">
    <?= $model->getContent() ?>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app', 'Request password reset');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?=Yii::t('app', 'Please fill out your email. A link to reset password will be sent there.');?></p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email') ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-grey']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app', 'Reset password');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-grey']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

            <?= $form->field($model, 'username') ?>

            <?= $form->field($model, 'email') ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <?= $form->field($model, 'nonAdv')->checkbox() ?>

            <div class="form-group">
                <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>